name: Deploy To S3

on:
  push:
    branches: [ main ]
  workflow_dispatch: # self trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout v2
        uses: actions/checkout@v2
        
      - name: Delete to s3
        env:
          AWS_S3_BUCKET: "pda-portfolio-nig"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          SOURCE_DIR: "./portfolioVer3"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
      
      #- name: Deploy To s3    
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #  run: |
      #    aws s3 cp \
      #      --recursive \
      #      --region ap-northeast-2 \
      #      ./portfolioVer3/ s3://pda-portfolio-nig

      - name: Invalidate CloudFront Cache # 새로 리소스를 업데이트할 때 기존 캐시 무효화
        uses: chetan/invalidate-cloudfront-action@master
        env:
          AWS_DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: '/*'
        continue-on-error: true
